global:
  accountDomain: fun.com

app:
  nameOverride: secrets
  image:
    repository: devops/secrets
    tag: latest
    pullPolicy: Always
  httpPort: 9090
  iamRole: users_shared_secrets_role
  livenessProbe:
    path: /
    failureThreshold: 30
  readinessProbe:
    path: /
    failureThreshold: 30
  ingress:
    fqdn: users-shared-secrets.fun.com
