global:
  accountDomain: scripbox.org

app:
  nameOverride: secrets
  image:
    repository: 826048892410.dkr.ecr.ap-south-1.amazonaws.com/devops/secrets
    tag: latest
    pullPolicy: Always
  httpPort: 9090
  iamRole: users_shared_secrets_role
  livenessProbe:
    path: /
    failureThreshold: 30
  readinessProbe:
    path: /
    failureThreshold: 30
  ingress:
    fqdn: users-shared-secrets.scripbox.org
